version: '3.3'

services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=root
      - MYSQL_DATABASE=moment_database2
      - MYSQL_PASSWORD=123456

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: api-moment
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
    depends_on:
      - db
    env_file:
      - .env